### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by joshuawe** [Chipato1/cortex_analysis#1]
Hello,

this seems like a promising project!
However, to get some understanding to what is going on. Do you want to add some sources to your readme?

**Comment by Chipato1** [comment]
Hi Josh,

To get a sense of where this stuff might be useful, it might be a good idea to look at some models and related publications. I definitely recommend Vox2Cortex, a model developed at TUM:

https://arxiv.org/abs/2203.09446
And this is the code: https://github.com/ai-med/Vox2Cortex

Basically, this code can be used to compare large sets of such predictions. 
I will add some functionality here as soon as I get some time for it and document a bit how this stuff can be used.
Thanks for your input!

Cheers, Carl
